# Cloudflare Tunnel configuration for Memory Palace
# This replaces Tailscale for public MCP endpoint exposure

tunnel: memory-palace
credentials-file: /home/rationallyprime/.cloudflared/memory-palace.json

ingress:
  # MCP endpoint for Claude.ai
  - hostname: memory-palace.sokrates.is
    service: http://localhost:8000
    originRequest:
      noTLSVerify: true
      connectTimeout: 120s
      tcpKeepAlive: 30s
      noHappyEyeballs: true
      keepAliveConnections: 1
      keepAliveTimeout: 120s
      http2Origin: false  # Disable HTTP/2 for better streaming
      disableChunkedEncoding: false  # Allow chunked responses for streaming
      
  # Catch-all for other requests
  - service: http_status:404