services:
  neo4j:
    image: neo4j:5.15.0
    container_name: memory-palace-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-password}
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  memory-palace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memory-palace-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - FRIEND_NAME=${FRIEND_NAME:-Hákon}
      - CLAUDE_NAME=${CLAUDE_NAME:-Claude}
      - PALACE_NAME=${PALACE_NAME:-Found Family Memory Palace}
      - LOG_LEVEL=INFO
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN:-pylf_v1_us_Y3M5BTg3KhZfGLSmM8VBKq4wJNzLGTtrW6zLc1LQHP6M}
    depends_on:
      neo4j:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src:ro  # Mount source code read-only for hot reload
    command: ["uvicorn", "memory_palace.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
