services:
  neo4j:
    image: neo4j:5.26.0
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-data:/data

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NEO4J_URI=bolt://neo4j:7687
    volumes:
      - ./src:/app/src
    depends_on:
      - neo4j
