"""Central constants module for Memory Palace.

This module contains all magic numbers and configuration constants
used throughout the application to avoid duplication and ensure consistency.
"""

# Salience thresholds and defaults
SALIENCE_MIN = 0.0
SALIENCE_MAX = 1.0
SALIENCE_DEFAULT = 0.3  # Default salience for new memories
SALIENCE_EVICTION_THRESHOLD = 0.05  # Memories below this are evicted
SALIENCE_DECAY_FACTOR_DEFAULT = 0.0154  # 45-day half-life

# Similarity search parameters
SIMILARITY_THRESHOLD_DEFAULT = 0.7
SIMILARITY_THRESHOLD_HIGH = 0.85
SIMILARITY_THRESHOLD_VERY_HIGH = 0.9
SIMILARITY_THRESHOLD_EXTREME = 0.95

# Embedding dimensions
EMBEDDING_DIMENSIONS_VOYAGE = 1536
EMBEDDING_DIMENSIONS_OPENAI = 1536

# Time windows and timeouts
RECENCY_WINDOW_DAYS_DEFAULT = 7
DECAY_WINDOW_DAYS_DEFAULT = 30
QUERY_TIMEOUT_MS_DEFAULT = 30000
QUERY_TIMEOUT_MS_MAX = 60000
CONNECTION_TIMEOUT_MS = 120000  # 2 minutes

# Batch and limit parameters
QUERY_LIMIT_DEFAULT = 20
QUERY_LIMIT_MAX = 100
RECALL_LIMIT_DEFAULT = 10
RECALL_LIMIT_MAX = 50
BATCH_SIZE_EMBEDDINGS = 50
VECTOR_SEARCH_K_MULTIPLIER = 3  # Multiply limit by this for initial retrieval

# Graph traversal
RELATIONSHIP_DEPTH_DEFAULT = 1
RELATIONSHIP_DEPTH_MAX = 3
RELATIONSHIP_STRENGTH_MIN = 0.0
RELATIONSHIP_STRENGTH_MAX = 1.0
RELATIONSHIP_STRENGTH_DEFAULT = 1.0

# Clustering parameters
MIN_CLUSTER_SIZE = 5
MIN_SAMPLES = 3
CLUSTER_SELECTION_EPSILON = 0.0
TOPIC_COHERENCE_MIN = 0.0
TOPIC_COHERENCE_MAX = 1.0

# Dream job intervals
SALIENCE_REFRESH_INTERVAL_MINUTES = 5
CLUSTER_RECENT_INTERVAL_HOURS = 1
NIGHTLY_RECLUSTER_HOUR = 3
NIGHTLY_RECLUSTER_MINUTE = 0
RECENT_MEMORY_CUTOFF_SECONDS = 86400  # 24 hours

# Error codes (grouped by category)
ERROR_CODE_GENERAL_BASE = 1000
ERROR_CODE_API_BASE = 2000
ERROR_CODE_DATABASE_BASE = 3000
ERROR_CODE_AI_ML_BASE = 4000
ERROR_CODE_INFRASTRUCTURE_BASE = 5000

# HTTP status codes (commonly used)
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_ERROR = 500
HTTP_SERVICE_UNAVAILABLE = 503

# OAuth/JWT parameters
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_MINUTES = 30
CLIENT_SECRET_EXPIRATION_NEVER = 0

# Neo4j specific
NEO4J_MAX_TRANSACTION_RETRY = 3
NEO4J_TRANSACTION_TIMEOUT_SECONDS = 30
